// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "@prisma/config";

const configParams: any = {
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
};

if (process.env.DATABASE_URL) {
  configParams.datasource = {
    url: process.env.DATABASE_URL,
  };
}

export default defineConfig(configParams);
